from __future__ import annotations

import logging

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from .llm_client import get_mentor_response
from .repository import load_curriculum, load_progression
from .retrieval import StaticSourceProvider
from .schemas import (
    LibrarianRequest,
    LibrarianResponse,
    LibrarianResult,
    MentorRequest,
    MentorResponse,
    SourceUsed,
)

logger = logging.getLogger(__name__)

app = FastAPI(title="42-training AI Gateway", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "service": "ai_gateway"}


@app.get("/api/v1/source-policy")
def source_policy() -> dict[str, object]:
    curriculum = load_curriculum()
    return curriculum["source_policy"]


def _static_fallback(request: MentorRequest, focus: str, active_course: str) -> dict[str, str]:
    """Hardcoded mentor response used when the LLM is unavailable."""
    if request.track_id == "shell":
        hint = "Reduis le probleme a une commande, un fichier, puis verifie le resultat avec `ls`, `cat` ou `echo $?`."
        next_action = "Ecris la commande exacte que tu veux tester, execute-la, puis note ce qui change dans le systeme de fichiers."
    elif request.track_id == "c":
        hint = "Separe bien logique, compilation et memoire. Commence toujours avec `cc -Wall -Wextra -Werror`."
        next_action = "Isole un cas minimal reproductible, compile, puis explique en une phrase ce que ton programme devrait faire."
    else:
        hint = "Garde Python simple d'abord: une fonction courte, une entree, une sortie. Pour l'IA, justifie toujours la source et le critere d'evaluation."
        next_action = "Reformule ton objectif en script minimal ou en pipeline RAG minimal avant d'ajouter une couche d'automatisation."

    return {
        "observation": f"Tu travailles sur {focus}. Le cours actif du profil est {active_course} et ta demande touche: {request.question[:120]}",
        "question": f"Quel est le plus petit resultat observable que tu veux obtenir sur {focus}?",
        "hint": hint,
        "next_action": next_action,
    }


def _build_provenance(
    curriculum: dict,
    track: dict,
    module: dict | None,
    source: str,
) -> tuple[list[SourceUsed], str, str]:
    """Build provenance metadata for a mentor response.

    Returns (sources_used, confidence_level, reasoning_trace).

    Confidence is derived from the tiers of sources actually consulted:
    - high: response based on official_42 curriculum data
    - medium: community docs or testers supplemented the response
    - low: fallback with no retrieval, or only solution metadata
    """
    sources: list[SourceUsed] = []

    # The curriculum JSON is always consulted (track/module lookup)
    sources.append(SourceUsed(tier="official_42", label="42 Lausanne curriculum data"))

    # If a module was matched, record it
    if module:
        sources.append(
            SourceUsed(
                tier="official_42",
                label=f"Module: {module['title']} (track: {track['id']})",
            )
        )

    # Add recommended resources that match the track
    for resource in curriculum.get("recommended_resources", []):
        if resource.get("tier") in ("official_42", "community_docs", "testers_and_tooling"):
            sources.append(
                SourceUsed(
                    tier=resource["tier"],
                    label=resource["label"],
                    url=resource.get("url"),
                )
            )

    # Determine confidence from source tiers and response source
    tiers_present = {s.tier for s in sources}
    if source == "llm" and "official_42" in tiers_present:
        confidence = "high"
    elif source == "fallback" and "official_42" in tiers_present:
        confidence = "medium"
    elif "community_docs" in tiers_present or "testers_and_tooling" in tiers_present:
        confidence = "medium"
    else:
        confidence = "low"

    # Build reasoning trace
    if source == "llm":
        trace = (
            f"Response generated by LLM using curriculum data for track '{track['id']}'"
            + (f", module '{module['id']}'" if module else "")
            + ". Source policy applied: official_42 as ground truth, community_docs for explanation."
        )
    else:
        trace = (
            f"Static fallback response using hardcoded guidance for track '{track['id']}'"
            + (f", module '{module['id']}'" if module else "")
            + ". LLM was unavailable. Confidence reduced accordingly."
        )

    return sources, confidence, trace


@app.post("/api/v1/mentor/respond", response_model=MentorResponse)
def mentor_respond(request: MentorRequest) -> MentorResponse:
    curriculum = load_curriculum()
    progression = load_progression()
    track = next((item for item in curriculum["tracks"] if item["id"] == request.track_id), None)
    if track is None:
        raise HTTPException(status_code=404, detail="Track not found")

    module = None
    if request.module_id:
        module = next((item for item in track.get("modules", []) if item["id"] == request.module_id), None)

    active_course = progression.get("learning_plan", {}).get("active_course", "shell")
    direct_solution_allowed = request.phase in {"advanced"}
    focus = module["title"] if module else track["title"]

    track_title = track["title"]
    module_title = module["title"] if module else None

    response_source = "llm"
    try:
        llm_result = get_mentor_response(request, track_title, module_title, active_course)
        observation = llm_result.get("observation", "")
        question = llm_result.get("question", "")
        hint = llm_result.get("hint", "")
        next_action = llm_result.get("next_action", "")
    except Exception:
        logger.warning("LLM call failed, using static fallback", exc_info=True)
        response_source = "fallback"
        fallback = _static_fallback(request, focus, active_course)
        observation = fallback["observation"]
        question = fallback["question"]
        hint = fallback["hint"]
        next_action = fallback["next_action"]

    sources_used, confidence_level, reasoning_trace = _build_provenance(
        curriculum, track, module, response_source,
    )

    return MentorResponse(
        status="ok",
        observation=observation,
        question=question,
        hint=hint,
        next_action=next_action,
        source_policy=[
            "official_42",
            "community_docs",
            "testers_and_tooling",
            "solution_metadata_only",
        ],
        direct_solution_allowed=direct_solution_allowed,
        sources_used=sources_used,
        confidence_level=confidence_level,
        reasoning_trace=reasoning_trace,
    )


# --- Tiers that are always blocked from Librarian results ---
BLOCKED_TIERS = {"blocked_solution_content"}

# Foundation and practice phases also block solution metadata
PHASE_RESTRICTED_TIERS: dict[str, set[str]] = {
    "foundation": {"solution_metadata"},
    "practice": {"solution_metadata"},
}


def _allowed_tiers(phase: str) -> list[str]:
    """Return tier ids the Librarian is allowed to serve for a given phase."""
    curriculum = load_curriculum()
    all_tiers = [t["id"] for t in curriculum["source_policy"]["tiers"]]
    excluded = BLOCKED_TIERS | PHASE_RESTRICTED_TIERS.get(phase, set())
    return [t for t in all_tiers if t not in excluded]


def _tier_labels() -> dict[str, str]:
    """Map tier id to human-readable label."""
    curriculum = load_curriculum()
    return {t["id"]: t["label"] for t in curriculum["source_policy"]["tiers"]}


@app.post("/api/v1/librarian/search", response_model=LibrarianResponse)
def librarian_search(request: LibrarianRequest) -> LibrarianResponse:
    allowed = _allowed_tiers(request.phase)
    labels = _tier_labels()
    provider = StaticSourceProvider()

    # Build search query — enrich with track/module context if provided
    search_query = request.query
    if request.module_id:
        search_query = f"{request.module_id} {search_query}"
    elif request.track_id:
        search_query = f"{request.track_id} {search_query}"

    raw_results = provider.search(
        query=request.query,
        tier_filter=allowed,
        max_results=request.max_results,
    )

    # Also search with enriched query if it differs
    if search_query != request.query:
        extra = provider.search(
            query=search_query,
            tier_filter=allowed,
            max_results=request.max_results,
        )
        seen = {(r.content, r.tier) for r in raw_results}
        for r in extra:
            if (r.content, r.tier) not in seen:
                raw_results.append(r)
                seen.add((r.content, r.tier))

    # Re-sort and truncate
    raw_results.sort(key=lambda r: r.confidence, reverse=True)
    raw_results = raw_results[: request.max_results]

    blocked = sorted(BLOCKED_TIERS | PHASE_RESTRICTED_TIERS.get(request.phase, set()))

    return LibrarianResponse(
        status="ok",
        query=request.query,
        results=[
            LibrarianResult(
                content=r.content,
                source_url=r.source_url,
                tier=r.tier,
                tier_label=labels.get(r.tier, r.tier),
                confidence=r.confidence,
            )
            for r in raw_results
        ],
        tiers_used=sorted({r.tier for r in raw_results}),
        blocked_tiers=blocked,
    )
